from snakemake.utils import min_version

##### set minimum snakemake version #####
min_version("7.16.0")


configfile: "config/config.yaml"


include: "rules/common.smk"
include: "rules/ref.smk"
include: "rules/align.smk"
include: "rules/count.smk"


rule all:
    input:
        rules.aggregate_counts.output,
