from snakemake.utils import min_version

##### set minimum snakemake version #####
min_version("7.16.0")


configfile: "config/config.yaml"


include: "rules/common.smk"
include: "rules/ref.smk"
include: "rules/trim.smk"
include: "rules/align.smk"
include: "rules/count.smk"
include: "rules/qc.smk" # should this be here or replace w line before? 


rule all:
    input:
        rules.prep_deseq.output,
