from snakemake.utils import min_version

##### set minimum snakemake version #####
min_version("7.8.5")


configfile: "config/config.yaml"


include: "rules/common.smk"
include: "rules/ref.smk"
include: "rules/align.smk"
include: "rules/count.smk"


rule all:
    input:
        expand(
            rules.tetranscripts_count.output,
            sample=samples["sample_name"],
        ),
