channels:
  - conda-forge
  - bioconda
  - nodefaults
dependencies:
  - python>=3.9
  - snakemake>=8
  - snakefmt
  - pandas
  - biopython
  - pre-commit
  - gh
  - snakemake-storage-plugin-ftp
  - snakemake-storage-plugin-http
