# path or URL to sample sheet (TSV format, columns: sample, condition, ...)
samples: config/samples.tsv


ref:
  # Ensembl species name: 
  # OPTIONS: homo_sapiens, mus_musculus
  species: homo_sapiens
  # Genome build
  # OPTIONS:
  #   - Homo_sapiens: GRCh38
  #   - Mus_musculus: GRCm38
  build: GRCh38
  # Ensembl release (make sure to take one where snpeff data is available, check 'snpEff databases' output)
  release: 107
  region: 

trimming:
  activate: False

# options are "multi" or "uniq"
tecount:
  mode: "uniq"
