samples: config/samples.tsv
outdir: results

ref:
  genome.fa: ngs-test-data/rnaseq/ref/genome.chr21.fa
  txome.fa: ngs-test-data/rnaseq/ref/txome.chr21.fa
  txome.gtf: ngs-test-data/rnaseq/ref/txome.chr21.gtf
  rmsk.gtf: ngs-test-data/rnaseq/ref/rmsk.chr21.gtf
  rmsk.locInd: https://labshare.cshl.edu/shares/mhammelllab/www-data/TElocal/prebuilt_indices/GRCh38_GENCODE_rmsk_TE.gtf.locInd.gz

trimming:
  activate: True

salmon:
  numBootstraps: 20
  extra: --gencode

de:
  # contrasts for the deseq2 results method
  contrasts:
    condition_Treatment_vs_Control:
      - Treatment
      - Control
  model: ~condition
  cutoffs:
    log2FoldChange: 0.1
    FDR: 1
