# path or URL to sample sheet (TSV format, columns: sample, condition, ...)
samples: .test/config/samples.tsv


ref:
  species: Homo_sapiens
  build: hg38
  region: chr21

trimming:
  activate: True
  cutadapt-pe: ""
  cutadapt-se: ""

tecount:
  mode: "uniq"