$schema: "https://json-schema.org/draft/2020-12/schema"

description: snakemake configuration file

type: object

properties:
  samples:
    type: string

  outdir:
    type: string

  species:
    type: string
    enum:
      - mouse
      - human

  ref:
    type: object
    properties:
      genome_fa:
        type: string
      txome_fa:
        type: string
      txome_gtf:
        type: string
    required:
      - genome.fa
      - txome.fa
      - txome.gtf
      - rmsk.gtf
      - rmsk.locInd

  trimming:
    type: object
    properties:
      activate:
        type: boolean

  filterTSOforTE:
    type: object
    properties:
      activate:
        type: boolean
      TSO:
        type: string
    required:
      - activate
      - TSO

required:
  - samples
  - outdir
  - species
  - ref
  - trimming
  - filterTSOforTE
